"""
ExitEngine_R — R-based exit management for professional trading.

Implements R-multiple exits:
  - 1R = initial risk (distance to stop loss)
  - At +0.8R: Move SL to breakeven + costs
  - At +1.0R: Close 33%
  - At +1.5R: Close another 33%
  - At +2.0R: Runner mode with trailing stop
  - If profit retraces 35% from peak: Close or tighten SL
  - If trade goes nowhere: Time-based exit

Usage:
    from Python.exit_engine_r import ExitEngineR, PositionRState
    engine = ExitEngineR(config)
    state = engine.calculate_exits(entry_price, stop_price, current_price, volume)
    action = engine.update_position(position_id, current_price, timestamp)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum, auto
from typing import Optional, Dict, Any, List, Tuple
from loguru import logger


class ExitAction(Enum):
    """Actions generated by exit engine."""
    HOLD = "hold"
    MOVE_TO_BREAKEVEN = "move_to_breakeven"
    PARTIAL_CLOSE_1 = "partial_close_1"  # First scale out
    PARTIAL_CLOSE_2 = "partial_close_2"  # Second scale out
    TRAIL_RUNNER = "trail_runner"  # Activate runner trailing
    CLOSE_PROFIT_RETRACE = "close_profit_retrace"
    CLOSE_TIME_EXIT = "close_time_exit"
    CLOSE_MAX_PROFIT = "close_max_profit"  # Hit runner target
    CLOSE_FULL = "close_full"


@dataclass
class RLevelConfig:
    """Configuration for R-level exits."""
    breakeven_trigger_r: float = 0.8
    scale_out_1_r: float = 1.0
    scale_out_1_pct: float = 0.33  # Close 33%
    scale_out_2_r: float = 1.5
    scale_out_2_pct: float = 0.33  # Close another 33%
    runner_trigger_r: float = 2.0
    profit_retrace_pct: float = 0.35  # Close if profit retraces 35%
    time_exit_minutes: int = 240  # Exit if no R within 4 hours
    max_runner_r: float = 4.0  # Take full profit at 4R
    trailing_distance_r: float = 1.0  # Trail 1R behind for runner


@dataclass
class PositionRState:
    """State tracking for R-based position management."""
    position_id: str
    symbol: str
    side: str  # "BUY" or "SELL"
    entry_price: float
    stop_price: float
    initial_volume: float
    current_volume: float
    initial_r: float  # Initial risk in price terms

    # Track levels reached
    breakeven_moved: bool = False
    scale_out_1_done: bool = False
    scale_out_2_done: bool = False
    runner_active: bool = False

    # Current trailing for runner mode
    current_trail_stop: Optional[float] = None
    highest_r_reached: float = 0.0
    highest_profit_price: Optional[float] = None

    # Time tracking
    entry_time: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    last_update: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def __post_init__(self):
        if self.initial_r <= 0:
            raise ValueError(f"Initial R must be positive, got {self.initial_r}")


@dataclass
class ExitRecommendation:
    """Recommendation from exit engine."""
    action: ExitAction
    current_r: float
    profit_pct: float
    volume_to_close: float  # 0 = none, partial = some, all = close full
    new_stop_price: Optional[float] = None
    reason: str = ""
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


class ExitEngineR:
    """
    R-based exit engine for professional trade management.
    """

    def __init__(self, config: Optional[Dict] = None):
        self.config = config or {}
        self.exit_config = RLevelConfig(
            breakeven_trigger_r=self.config.get("breakeven_trigger_r", 0.8),
            scale_out_1_r=self.config.get("scale_out_1_r", 1.0),
            scale_out_1_pct=self.config.get("scale_out_1_pct", 0.33),
            scale_out_2_r=self.config.get("scale_out_2_r", 1.5),
            scale_out_2_pct=self.config.get("scale_out_2_pct", 0.33),
            runner_trigger_r=self.config.get("runner_trigger_r", 2.0),
            profit_retrace_pct=self.config.get("profit_retrace_pct", 0.35),
            time_exit_minutes=self.config.get("time_exit_minutes", 240),
            max_runner_r=self.config.get("max_runner_r", 4.0),
            trailing_distance_r=self.config.get("trailing_distance_r", 1.0),
        )

        # Track all managed positions
        self._positions: Dict[str, PositionRState] = {}
        self._history: List[Dict] = []

    def register_position(
        self,
        position_id: str,
        symbol: str,
        side: str,
        entry_price: float,
        stop_price: float,
        volume: float,
        timestamp: Optional[datetime] = None
    ) -> PositionRState:
        """
        Register a new position for R-based exit management.

        Args:
            position_id: Unique identifier
            symbol: Trading symbol
            side: "BUY" or "SELL"
            entry_price: Entry price
            stop_price: Stop loss price
            volume: Position volume
            timestamp: Entry timestamp
        """
        initial_r = abs(entry_price - stop_price)
        if initial_r == 0:
            raise ValueError("Initial R cannot be zero - entry and stop prices are identical")

        state = PositionRState(
            position_id=position_id,
            symbol=symbol,
            side=side.upper(),
            entry_price=entry_price,
            stop_price=stop_price,
            initial_volume=volume,
            current_volume=volume,
            initial_r=initial_r,
            entry_time=timestamp or datetime.now(timezone.utc)
        )

        self._positions[position_id] = state
        logger.info(f"Registered position {position_id} for R-exit: {side} {volume} lots "
                   f"at {entry_price}, R={initial_r:.5f}")

        return state

    def calculate_current_r(self, state: PositionRState, current_price: float) -> float:
        """Calculate current R multiple."""
        if state.side == "BUY":
            profit = current_price - state.entry_price
        else:
            profit = state.entry_price - current_price

        return profit / state.initial_r if state.initial_r > 0 else 0.0

    def update_position(
        self,
        position_id: str,
        current_price: float,
        timestamp: Optional[datetime] = None
    ) -> ExitRecommendation:
        """
        Update position and generate exit recommendation.

        Args:
            position_id: Position identifier
            current_price: Current market price
            timestamp: Update timestamp

        Returns:
            ExitRecommendation with action to take
        """
        if position_id not in self._positions:
            return ExitRecommendation(
                action=ExitAction.HOLD,
                current_r=0.0,
                profit_pct=0.0,
                volume_to_close=0.0,
                reason="Position not found"
            )

        state = self._positions[position_id]
        now = timestamp or datetime.now(timezone.utc)
        state.last_update = now

        current_r = self.calculate_current_r(state, current_price)

        # Update highest R reached
        if current_r > state.highest_r_reached:
            state.highest_r_reached = current_r

        # Update highest profit price (for retrace detection)
        if state.side == "BUY":
            if state.highest_profit_price is None or current_price > state.highest_profit_price:
                state.highest_profit_price = current_price
        else:
            if state.highest_profit_price is None or current_price < state.highest_profit_price:
                state.highest_profit_price = current_price

        profit_pct = (current_r * state.initial_r / state.entry_price) * 100

        # Check time-based exit
        time_held_minutes = (now - state.entry_time).total_seconds() / 60
        if time_held_minutes > self.exit_config.time_exit_minutes:
            if current_r < 0.5:  # Not profitable enough
                return ExitRecommendation(
                    action=ExitAction.CLOSE_TIME_EXIT,
                    current_r=current_r,
                    profit_pct=profit_pct,
                    volume_to_close=state.current_volume,
                    reason=f"Time exit: {time_held_minutes:.0f}min held, only {current_r:.2f}R"
                )

        # Check max runner R reached
        if state.runner_active and current_r >= self.exit_config.max_runner_r:
            return ExitRecommendation(
                action=ExitAction.CLOSE_MAX_PROFIT,
                current_r=current_r,
                profit_pct=profit_pct,
                volume_to_close=state.current_volume,
                reason=f"Max runner R reached: {current_r:.2f}R"
            )

        # Check profit retrace (for positions that have made significant profit)
        if state.highest_r_reached > 1.0:
            retrace_threshold = state.highest_r_reached * (1 - self.exit_config.profit_retrace_pct)
            if current_r < retrace_threshold:
                # Partial close if in runner mode
                if state.runner_active:
                    return ExitRecommendation(
                        action=ExitAction.CLOSE_PROFIT_RETRACE,
                        current_r=current_r,
                        profit_pct=profit_pct,
                        volume_to_close=state.current_volume * 0.5,  # Close half
                        new_stop_price=self._calculate_trail_stop(state, current_r),
                        reason=f"Profit retraced {self.exit_config.profit_retrace_pct*100:.0f}% "
                               f"from {state.highest_r_reached:.2f}R to {current_r:.2f}R"
                    )
                else:
                    return ExitRecommendation(
                        action=ExitAction.CLOSE_PROFIT_RETRACE,
                        current_r=current_r,
                        profit_pct=profit_pct,
                        volume_to_close=state.current_volume,
                        reason=f"Profit retraced {self.exit_config.profit_retrace_pct*100:.0f}%"
                    )

        # Runner mode trailing update
        if state.runner_active:
            new_trail = self._calculate_trail_stop(state, current_r)
            if new_trail != state.current_trail_stop:
                state.current_trail_stop = new_trail
                return ExitRecommendation(
                    action=ExitAction.TRAIL_RUNNER,
                    current_r=current_r,
                    profit_pct=profit_pct,
                    volume_to_close=0.0,
                    new_stop_price=new_trail,
                    reason=f"Updated runner trail to {new_trail:.5f}"
                )

        # Check R-level exits

        # Breakeven trigger
        if not state.breakeven_moved and current_r >= self.exit_config.breakeven_trigger_r:
            # Move SL to entry + small buffer
            buffer = state.initial_r * 0.1  # 0.1R buffer
            if state.side == "BUY":
                new_stop = state.entry_price + buffer
            else:
                new_stop = state.entry_price - buffer

            state.breakeven_moved = True
            return ExitRecommendation(
                action=ExitAction.MOVE_TO_BREAKEVEN,
                current_r=current_r,
                profit_pct=profit_pct,
                volume_to_close=0.0,
                new_stop_price=new_stop,
                reason=f"Breakeven triggered at {current_r:.2f}R"
            )

        # Scale out 1
        if not state.scale_out_1_done and current_r >= self.exit_config.scale_out_1_r:
            close_volume = state.initial_volume * self.exit_config.scale_out_1_pct
            state.current_volume -= close_volume
            state.scale_out_1_done = True

            return ExitRecommendation(
                action=ExitAction.PARTIAL_CLOSE_1,
                current_r=current_r,
                profit_pct=profit_pct,
                volume_to_close=close_volume,
                reason=f"Scale out 1 at {current_r:.2f}R, closed {close_volume:.2f} lots"
            )

        # Scale out 2
        if not state.scale_out_2_done and current_r >= self.exit_config.scale_out_2_r:
            close_volume = state.initial_volume * self.exit_config.scale_out_2_pct
            state.current_volume -= close_volume
            state.scale_out_2_done = True

            return ExitRecommendation(
                action=ExitAction.PARTIAL_CLOSE_2,
                current_r=current_r,
                profit_pct=profit_pct,
                volume_to_close=close_volume,
                reason=f"Scale out 2 at {current_r:.2f}R, closed {close_volume:.2f} lots"
            )

        # Runner trigger
        if not state.runner_active and current_r >= self.exit_config.runner_trigger_r:
            state.runner_active = True
            state.current_trail_stop = self._calculate_trail_stop(state, current_r)

            return ExitRecommendation(
                action=ExitAction.TRAIL_RUNNER,
                current_r=current_r,
                profit_pct=profit_pct,
                volume_to_close=0.0,
                new_stop_price=state.current_trail_stop,
                reason=f"Runner mode activated at {current_r:.2f}R"
            )

        # Default: hold
        return ExitRecommendation(
            action=ExitAction.HOLD,
            current_r=current_r,
            profit_pct=profit_pct,
            volume_to_close=0.0,
            reason=f"Holding at {current_r:.2f}R"
        )

    def _calculate_trail_stop(self, state: PositionRState, current_r: float) -> float:
        """Calculate trailing stop for runner mode."""
        trail_distance = state.initial_r * self.exit_config.trailing_distance_r
        min_stop = state.entry_price + (state.initial_r * 1.0) if state.side == "BUY" else state.entry_price - (state.initial_r * 1.0)

        if state.side == "BUY":
            new_stop = max(
                state.entry_price + (state.initial_r * (current_r - 1.0)),  # Trail 1R behind
                min_stop
            )
        else:
            new_stop = min(
                state.entry_price - (state.initial_r * (current_r - 1.0)),
                min_stop
            )

        return new_stop

    def remove_position(self, position_id: str):
        """Remove position from tracking (after full close)."""
        if position_id in self._positions:
            state = self._positions.pop(position_id)
            self._history.append({
                "position_id": position_id,
                "symbol": state.symbol,
                "max_r": state.highest_r_reached,
                "entry_time": state.entry_time.isoformat(),
                "exit_time": datetime.now(timezone.utc).isoformat(),
            })
            logger.info(f"Removed position {position_id} from exit tracking (max R: {state.highest_r_reached:.2f})")

    def get_position_state(self, position_id: str) -> Optional[PositionRState]:
        """Get current state for a position."""
        return self._positions.get(position_id)

    def get_all_positions(self) -> List[PositionRState]:
        """Get all tracked positions."""
        return list(self._positions.values())

    def get_summary(self) -> Dict[str, Any]:
        """Get summary of exit engine state."""
        active_positions = len(self._positions)
        runner_count = sum(1 for p in self._positions.values() if p.runner_active)

        avg_max_r = 0.0
        if self._history:
            avg_max_r = sum(h.get("max_r", 0) for h in self._history) / len(self._history)

        return {
            "active_positions": active_positions,
            "runner_positions": runner_count,
            "historical_positions": len(self._history),
            "avg_max_r_historical": round(avg_max_r, 2),
            "config": {
                "breakeven_r": self.exit_config.breakeven_trigger_r,
                "scale_1_r": self.exit_config.scale_out_1_r,
                "scale_2_r": self.exit_config.scale_out_2_r,
                "runner_r": self.exit_config.runner_trigger_r,
                "max_runner_r": self.exit_config.max_runner_r,
            }
        }


# Convenience function for quick usage
def calculate_r_levels(
    entry_price: float,
    stop_price: float,
    r_targets: List[float] = None
) -> Dict[float, float]:
    """
    Calculate price levels for given R multiples.

    Args:
        entry_price: Entry price
        stop_price: Stop price
        r_targets: List of R targets (default [0.8, 1.0, 1.5, 2.0, 3.0, 4.0])

    Returns:
        Dict mapping R level to price
    """
    if r_targets is None:
        r_targets = [0.8, 1.0, 1.5, 2.0, 3.0, 4.0]

    initial_r = abs(entry_price - stop_price)
    is_long = entry_price > stop_price

    levels = {}
    for r in r_targets:
        if is_long:
            levels[r] = entry_price + (initial_r * r)
        else:
            levels[r] = entry_price - (initial_r * r)

    return levels