"""
StrategySelector — Select trading strategy based on market regime.

Three strategy modules:
  1. TrendModule — Trades pullbacks in established trends
  2. MeanReversionModule — Trades price extensions in ranging markets
  3. BreakoutModule — Trades range breakouts with momentum confirmation

Usage:
    from Python.strategy_selector import StrategySelector, StrategyModule
    selector = StrategySelector(config)
    strategy = selector.select(regime, df)
    if strategy:
        signal = strategy.generate_signal(symbol, df)
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from enum import Enum, auto
from typing import Optional, Dict, Any, List, Tuple
import numpy as np
import pandas as pd
from loguru import logger

from Python.market_guardian import MarketRegime, RegimeResult


class SignalType(Enum):
    """Types of trading signals."""
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


@dataclass
class StrategySignal:
    """Signal generated by a strategy module."""
    signal_type: SignalType
    confidence: float  # 0-1
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    risk_r: Optional[float] = None  # Initial risk in R units
    reason: str = ""
    timeframe: str = "M5"
    strategy_name: str = ""
    invalidation_price: Optional[float] = None  # Price level that invalidates setup


@dataclass
class StrategyContext:
    """Context for strategy selection."""
    regime: MarketRegime
    atr_14: float
    adx_14: float
    rsi_14: float
    trend_direction: int  # -1, 0, 1
    volatility_percentile: float
    spread_bps: float
    session_quality: str  # "high", "medium", "low"


class StrategyModule(ABC):
    """Abstract base class for strategy modules."""

    def __init__(self, config: Optional[Dict] = None):
        self.config = config or {}
        self.name = self.__class__.__name__.replace("Module", "").lower()
        self.enabled = True

    @abstractmethod
    def is_applicable(self, context: StrategyContext) -> bool:
        """Check if this strategy is applicable to current conditions."""
        pass

    @abstractmethod
    def generate_signal(self, symbol: str, df: pd.DataFrame, context: StrategyContext) -> StrategySignal:
        """Generate trading signal."""
        pass

    @abstractmethod
    def calculate_score(self, context: StrategyContext) -> float:
        """Calculate strategy fit score (0-1)."""
        pass

    def _calculate_atr(self, df: pd.DataFrame, period: int = 14) -> float:
        """Calculate ATR."""
        high_low = df['high'] - df['low']
        high_close = abs(df['high'] - df['close'].shift())
        low_close = abs(df['low'] - df['close'].shift())
        tr = pd.concat([high_low, high_close, low_close], axis=1).max(axis=1)
        atr = tr.rolling(window=period).mean().iloc[-1]
        return atr if not np.isnan(atr) else 0.0

    def _calculate_ema(self, series: pd.Series, period: int) -> pd.Series:
        """Calculate EMA."""
        return series.ewm(span=period, adjust=False).mean()

    def _calculate_rsi(self, series: pd.Series, period: int = 14) -> float:
        """Calculate RSI."""
        delta = series.diff()
        gain = delta.where(delta > 0, 0)
        loss = -delta.where(delta < 0, 0)
        avg_gain = gain.rolling(window=period).mean()
        avg_loss = loss.rolling(window=period).mean()
        rs = avg_gain / avg_loss
        rsi = 100 - (100 / (1 + rs))
        return rsi.iloc[-1] if not np.isnan(rsi.iloc[-1]) else 50.0


class TrendModule(StrategyModule):
    """
    Trend following strategy module.

    Trades pullbacks in established trends:
    - Price above/below higher timeframe EMA
    - Pullback to support/resistance
    - Momentum resumes
    - Spread normal, no news
    """

    def __init__(self, config: Optional[Dict] = None):
        super().__init__(config)
        self.ema_fast = self.config.get("trend_ema_fast", 9)
        self.ema_slow = self.config.get("trend_ema_slow", 21)
        self.pullback_threshold = self.config.get("pullback_threshold", 0.5)  # % of ATR
        self.trend_adx_min = self.config.get("trend_adx_min", 25)
        self.min_bars = 30

    def is_applicable(self, context: StrategyContext) -> bool:
        """Trend module works in trending regimes."""
        return context.regime in {
            MarketRegime.MED_VOL_TREND,
            MarketRegime.HIGH_VOL_BREAKOUT
        } and context.adx_14 >= self.trend_adx_min

    def calculate_score(self, context: StrategyContext) -> float:
        """Score trend fit."""
        if not self.is_applicable(context):
            return 0.0

        score = 0.5

        # Higher ADX = better trend
        if context.adx_14 > 30:
            score += 0.2
        elif context.adx_14 > 25:
            score += 0.1

        # Medium volatility preferred over high
        if context.regime == MarketRegime.MED_VOL_TREND:
            score += 0.2

        return min(score, 1.0)

    def generate_signal(self, symbol: str, df: pd.DataFrame, context: StrategyContext) -> StrategySignal:
        """Generate trend pullback signal."""
        if len(df) < self.min_bars:
            return StrategySignal(SignalType.HOLD, 0.0, reason="Insufficient data")

        current_price = df['close'].iloc[-1]
        atr = self._calculate_atr(df)

        # Calculate EMAs
        ema_fast = self._calculate_ema(df['close'], self.ema_fast)
        ema_slow = self._calculate_ema(df['close'], self.ema_slow)

        # Determine trend
        price_above_slow = current_price > ema_slow.iloc[-1]
        fast_above_slow = ema_fast.iloc[-1] > ema_slow.iloc[-1]

        # Look for pullback
        recent_high = df['high'].rolling(window=10).max().iloc[-1]
        recent_low = df['low'].rolling(window=10).min().iloc[-1]

        # Check for pullback to EMA
        pullback_to_fast = abs(current_price - ema_fast.iloc[-1]) < atr * 0.5
        pullback_to_slow = abs(current_price - ema_slow.iloc[-1]) < atr * 0.5

        signal_type = SignalType.HOLD
        confidence = 0.0
        reason = "No clear setup"
        entry = stop = target = None
        risk_r = 1.0

        # Uptrend pullback buy
        if price_above_slow and fast_above_slow and (pullback_to_fast or pullback_to_slow):
            signal_type = SignalType.BUY
            confidence = min(context.adx_14 / 40, 0.9)
            entry = current_price
            stop = ema_slow.iloc[-1] - atr * 0.5  # Below EMA
            target = entry + (entry - stop) * 2.0  # 2:1 R/R
            reason = f"Uptrend pullback, ADX {context.adx_14:.1f}"
            risk_r = (entry - stop) / atr if atr > 0 else 1.0

        # Downtrend pullback sell
        elif not price_above_slow and not fast_above_slow and (pullback_to_fast or pullback_to_slow):
            signal_type = SignalType.SELL
            confidence = min(context.adx_14 / 40, 0.9)
            entry = current_price
            stop = ema_slow.iloc[-1] + atr * 0.5  # Above EMA
            target = entry - (stop - entry) * 2.0  # 2:1 R/R
            reason = f"Downtrend pullback, ADX {context.adx_14:.1f}"
            risk_r = (stop - entry) / atr if atr > 0 else 1.0

        return StrategySignal(
            signal_type=signal_type,
            confidence=confidence,
            entry_price=entry,
            stop_loss=stop,
            take_profit=target,
            risk_r=risk_r,
            reason=reason,
            strategy_name="trend_pullback",
            invalidation_price=stop
        )


class MeanReversionModule(StrategyModule):
    """
    Mean reversion strategy module.

    Trades price extensions in ranging markets:
    - Price stretched from mean (BB bands)
    - Volatility is calm
    - Market is ranging
    - Profit target is nearby
    """

    def __init__(self, config: Optional[Dict] = None):
        super().__init__(config)
        self.bb_period = self.config.get("mr_bb_period", 20)
        self.bb_std = self.config.get("mr_bb_std", 2.0)
        self.rsi_overbought = self.config.get("mr_rsi_overbought", 70)
        self.rsi_oversold = self.config.get("mr_rsi_oversold", 30)
        self.min_bars = 30

    def is_applicable(self, context: StrategyContext) -> bool:
        """Mean reversion works in ranging, low-vol regimes."""
        return context.regime in {
            MarketRegime.LOW_VOL_RANGE
        } and context.adx_14 < 25

    def calculate_score(self, context: StrategyContext) -> float:
        """Score mean reversion fit."""
        if not self.is_applicable(context):
            return 0.0

        score = 0.5

        # Low ADX is good for mean reversion
        if context.adx_14 < 20:
            score += 0.3
        elif context.adx_14 < 25:
            score += 0.15

        return min(score, 1.0)

    def generate_signal(self, symbol: str, df: pd.DataFrame, context: StrategyContext) -> StrategySignal:
        """Generate mean reversion signal."""
        if len(df) < self.min_bars:
            return StrategySignal(SignalType.HOLD, 0.0, reason="Insufficient data")

        current_price = df['close'].iloc[-1]
        atr = self._calculate_atr(df)

        # Calculate Bollinger Bands
        sma = df['close'].rolling(window=self.bb_period).mean()
        std = df['close'].rolling(window=self.bb_period).std()
        upper = sma + (std * self.bb_std)
        lower = sma - (std * self.bb_std)

        rsi = self._calculate_rsi(df['close'], 14)

        # Check position relative to bands
        near_upper = current_price >= upper.iloc[-1] * 0.995
        near_lower = current_price <= lower.iloc[-1] * 1.005

        signal_type = SignalType.HOLD
        confidence = 0.0
        reason = "No clear setup"
        entry = stop = target = None

        # Sell overbought
        if near_upper and rsi > self.rsi_overbought - 5:
            signal_type = SignalType.SELL
            confidence = min((rsi - 60) / 30, 0.9)
            entry = current_price
            stop = upper.iloc[-1] + atr * 0.5
            target = sma.iloc[-1]  # Target the mean
            reason = f"Overbought mean reversion, RSI {rsi:.1f}"

        # Buy oversold
        elif near_lower and rsi < self.rsi_oversold + 5:
            signal_type = SignalType.BUY
            confidence = min((40 - rsi) / 30, 0.9)
            entry = current_price
            stop = lower.iloc[-1] - atr * 0.5
            target = sma.iloc[-1]  # Target the mean
            reason = f"Oversold mean reversion, RSI {rsi:.1f}"

        risk_r = abs(entry - stop) / atr if atr > 0 and entry and stop else 1.0

        return StrategySignal(
            signal_type=signal_type,
            confidence=confidence,
            entry_price=entry,
            stop_loss=stop,
            take_profit=target,
            risk_r=risk_r,
            reason=reason,
            strategy_name="mean_reversion",
            invalidation_price=stop
        )


class BreakoutModule(StrategyModule):
    """
    Breakout strategy module.

    Trades range breakouts:
    - Range compression (low volatility)
    - Volume/ATR expansion confirms
    - News filter is clean
    - Spread is acceptable
    """

    def __init__(self, config: Optional[Dict] = None):
        super().__init__(config)
        self.range_lookback = self.config.get("bo_range_lookback", 20)
        self.breakout_threshold = self.config.get("bo_threshold", 0.3)  # % of range
        self.volume_confirm = self.config.get("bo_volume_confirm", True)
        self.min_bars = 30

    def is_applicable(self, context: StrategyContext) -> bool:
        """Breakout works in breakout regime."""
        return context.regime == MarketRegime.HIGH_VOL_BREAKOUT

    def calculate_score(self, context: StrategyContext) -> float:
        """Score breakout fit."""
        if not self.is_applicable(context):
            return 0.0

        score = 0.6  # Base score for breakout regime

        # Higher ADX is better for breakouts
        if context.adx_14 > 35:
            score += 0.2

        return min(score, 1.0)

    def generate_signal(self, symbol: str, df: pd.DataFrame, context: StrategyContext) -> StrategySignal:
        """Generate breakout signal."""
        if len(df) < self.min_bars:
            return StrategySignal(SignalType.HOLD, 0.0, reason="Insufficient data")

        current_price = df['close'].iloc[-1]
        atr = self._calculate_atr(df)

        # Find range
        recent = df.tail(self.range_lookback)
        range_high = recent['high'].max()
        range_low = recent['low'].min()
        range_size = range_high - range_low

        # Check for breakout
        above_high = current_price > range_high * (1 - self.breakout_threshold)
        below_low = current_price < range_low * (1 + self.breakout_threshold)

        # ATR expansion confirmation
        atr_recent = df['close'].diff().abs().tail(10).mean()
        atr_previous = df['close'].diff().abs().tail(20).head(10).mean()
        atr_expanding = atr_recent > atr_previous * 1.2 if atr_previous > 0 else False

        signal_type = SignalType.HOLD
        confidence = 0.0
        reason = "No breakout detected"
        entry = stop = target = None

        if above_high and atr_expanding:
            signal_type = SignalType.BUY
            confidence = 0.7
            entry = current_price
            stop = range_low  # Full range as stop
            target = entry + range_size * 1.5
            reason = f"Breakout above {self.range_lookback}bar range"

        elif below_low and atr_expanding:
            signal_type = SignalType.SELL
            confidence = 0.7
            entry = current_price
            stop = range_high  # Full range as stop
            target = entry - range_size * 1.5
            reason = f"Breakdown below {self.range_lookback}bar range"

        risk_r = abs(entry - stop) / atr if atr > 0 and entry and stop else 1.0

        return StrategySignal(
            signal_type=signal_type,
            confidence=confidence,
            entry_price=entry,
            stop_loss=stop,
            take_profit=target,
            risk_r=risk_r,
            reason=reason,
            strategy_name="breakout",
            invalidation_price=stop
        )


class StrategySelector:
    """
    Selects and manages strategy modules.
    Routes trades to appropriate strategy based on regime.
    """

    def __init__(self, config: Optional[Dict] = None):
        self.config = config or {}
        self.modules: List[StrategyModule] = [
            TrendModule(config),
            MeanReversionModule(config),
            BreakoutModule(config)
        ]
        self.min_confidence = self.config.get("min_strategy_confidence", 0.6)
        self._last_signals: Dict[str, StrategySignal] = {}

    def select(self, context: StrategyContext) -> Optional[StrategyModule]:
        """
        Select best strategy module for current conditions.
        Returns None if no suitable strategy found.
        """
        scores = []
        for module in self.modules:
            if not module.enabled:
                continue
            score = module.calculate_score(context)
            if score > 0:
                scores.append((module, score))

        if not scores:
            return None

        # Sort by score descending
        scores.sort(key=lambda x: x[1], reverse=True)
        best_module, best_score = scores[0]

        if best_score < self.min_confidence:
            logger.debug(f"Best strategy {best_module.name} score {best_score:.2f} below threshold")
            return None

        logger.debug(f"Selected strategy: {best_module.name} (score: {best_score:.2f})")
        return best_module

    def generate_signal(
        self,
        symbol: str,
        df: pd.DataFrame,
        context: StrategyContext
    ) -> StrategySignal:
        """
        Generate signal using best strategy for current conditions.
        """
        strategy = self.select(context)

        if strategy is None:
            return StrategySignal(
                signal_type=SignalType.HOLD,
                confidence=0.0,
                reason=f"No strategy suitable for regime {context.regime.value}"
            )

        signal = strategy.generate_signal(symbol, df, context)
        signal.strategy_name = strategy.name

        # Cache signal
        self._last_signals[symbol] = signal

        return signal

    def get_last_signal(self, symbol: str) -> Optional[StrategySignal]:
        """Get last signal for a symbol."""
        return self._last_signals.get(symbol)

    def disable_module(self, module_name: str):
        """Disable a strategy module by name."""
        for module in self.modules:
            if module.name == module_name.lower():
                module.enabled = False
                logger.info(f"Disabled strategy module: {module_name}")
                return True
        return False

    def enable_module(self, module_name: str):
        """Enable a strategy module by name."""
        for module in self.modules:
            if module.name == module_name.lower():
                module.enabled = True
                logger.info(f"Enabled strategy module: {module_name}")
                return True
        return False


# Convenience function
def select_strategy_for_regime(
    regime: MarketRegime,
    config: Optional[Dict] = None
) -> Optional[str]:
    """
    Quick function to get strategy name for a regime.

    Returns:
        Strategy name or None if no suitable strategy
    """
    regime_strategy_map = {
        MarketRegime.LOW_VOL_RANGE: "mean_reversion",
        MarketRegime.MED_VOL_TREND: "trend",
        MarketRegime.HIGH_VOL_BREAKOUT: "breakout",
    }
    return regime_strategy_map.get(regime)